version: "3.7"
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "./.volume/postgres:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  localstack:
    build:
      context: localstack
      dockerfile: Dockerfile
    image: localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    user: ${MY_UID}:${MY_GID}
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./.volume/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
