# Generated by Django 5.0.1 on 2024-01-07 23:17

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
                ("sequence", models.IntegerField()),
                ("description", martor.models.MartorField(blank=True, null=True)),
                ("banner", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
